trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build, Test, and Publish'
  steps:
  - checkout: self
    submodules: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '6.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: Docker@2
    inputs:
      command: 'login'
      
  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'dckr_pat_hWVcFqfPd-xsbJOssUgQeqergu0'
      repository: 'darakimberlys/whathaveyoulost'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)